version: '3.8'
services:
  redis:
    image: redis:7
    container_name: kakao-redis
    ports:
      - "6379:6379"
  mysql:
    image: mysql:8
    container_name: kakao-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: kakao
      MYSQL_USER: kakao
      MYSQL_PASSWORD: kakao1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
